name: Backdoor1
version: ${project.version}
main: me.lunacore.backdoor1.iii
permissions:
  I.III:
    description: run om
    default: true
commands:
  om:
    description: om
    permission: I.III
    aliases: iii
    dp:
    description: on
    permission: I.III
    aliases: iiii
